### ISSUE TITLE
Better animations

### ISSUE THREAD

**Issue by swapnens** [bprinty/animation#10]
The animations could be better and well-spaced.
For example, the dots do not work with any text because that text gets overwritten

**Comment by bprinty** [comment]
Can you post a gif showing how text gets overwritten for the `dots` animation? That will help me understand how to appropriately change animations.

Thanks!

**Comment by swapnens** [comment]
![1](https://user-images.githubusercontent.com/25797140/93785190-6e35fc80-fc4b-11ea-956a-73e8cf4d97a6.gif)
Here you go

**Comment by swapnens** [comment]
I have made a pull request to solve this issue.

**Comment by bprinty** [comment]
Thanks! I merged in the fix. Going to re-release on PyPi as v0.0.7.
