### ISSUE TITLE
Package has been removed from `pip` repo

### ISSUE THREAD

**Issue by serain** [bprinty/animation#2]
animation is unfortunately no longer available on `pip`.

Can you re-publish? If not, do you mind if I re-publish it?

This is in my opinion the most elegant spinning animation for Python and I use it in a couple of projects :)

**Comment by bprinty** [comment]
Sure thing! I took it down because I didn't think it was getting any use. Just pushed it back up to PyPi.

**Comment by serain** [comment]
Thanks!

**Comment by serain** [comment]
@bprinty 

Getting the following when I try to `pip install` it:

```
Collecting animation
  Downloading animation-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-utjy2cf6/animation/setup.py", line 19, in <module>
        with open('requirements.txt', 'r') as reqs:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by bprinty** [comment]
Thanks for the heads up! I just pushed a new patch release (0.0.3) where this issue is fixed.
