### ISSUE TITLE
No option to add custom text to wait decorators

### ISSUE THREAD

**Issue by feltrite** [bprinty/animation#3]
The only way to use a custom text animation is within the function im writing, there is no option to add extra text :(

**Comment by bprinty** [comment]
Hey, thanks for the pull requests! I just merged them in and pushed a new release to pypi (0.0.5). The changes you made addressed this issue, correct?

**Comment by feltrite** [comment]
@bprinty yes thay have :) 
kind of bold to just directly merge them from a strange without checking 😜
