### ISSUE TITLE
Removes an extra line on completion

### ISSUE THREAD

**Issue by swapnens** [bprinty/animation#8]
When the animation completes, it removes and extra line than it should.
Steps to reproduce:
Use Animation.Wait()

**Comment by bprinty** [comment]
Can you post a gif showing how text gets removed? Removing the line is intentional to clean up the screen between animation calls.

Thanks!

**Comment by swapnens** [comment]
Here you go
![1](https://user-images.githubusercontent.com/25797140/93785049-447cd580-fc4b-11ea-852f-e5743a6fe6db.gif)

**Comment by swapnens** [comment]
Here you go
![2](https://user-images.githubusercontent.com/25797140/93785362-a3dae580-fc4b-11ea-8d53-a09fc45c89dc.gif)

**Comment by swapnens** [comment]
I have made a pull request to solve this.

**Comment by bprinty** [comment]
Thanks! I merged in the fix. Going to re-release on PyPi as v0.0.7.
